dist: trusty
language: node_js
node_js:
  - "stable"
skip_cleanup: true
stages:
  - build
  - name: deploy
    if: branch = master AND type = push
jobs:
  include:
    - stage: build
      before_install:
        - npm install -g npm@latest
        - npm install -g node-gyp
        - npm install -g coffeescript
      install:
        - npm install
      script:
        - ./make.coffee dev
    - stage: deploy
      script:
        - git checkout master
        - ./make.coffee dev
        - git add .
        - >
          if [ ! -z "$(git status --untracked-files=no --porcelain)" ]; then
            git commit -m "HTML updated";
            git push https://${GITHUB_TOKEN}@github.com/driver733/kotlin-vs-java.git;
          else
            echo "No changes in generated HTML files";
          fi
