dist: trusty
language: node_js
node_js:
  - "stable"
skip_cleanup: true
stages:
  - name: build
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: build
      before_install:
        - npm install -g npm@latest
        - npm install -g node-gyp
        - npm install -g coffeescript
      install:
        - npm install
      script:
        - ./make.coffee dev
    - stage: deploy
      if: branch = master
      script:
        - ./make.coffee dev
        - git checkout master
        - git add .
        - git commit -m "Regenerated HTML"
        - git push https://${GITHUB_TOKEN}@github.com/driver733/kotlin-vs-java.git
